### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by MahdiNazemi** [infokiller/web-search-navigator#427]
Is it possible to have a "fancy" highlight option similar to [this code](https://github.com/jchafik/google-search-shortcuts/blob/edb7b18978dc9fb5654309cd1d547471ed80fb8a/css/highlight.css) used in [this extension](https://chrome.google.com/webstore/detail/google-search-keyboard-sh/iobmefdldoplhmonnnkchglfdeepnfhd)?

Screenshot:
<img width="1080" alt="Screen Shot 2022-09-02 at 6 11 52 PM" src="https://user-images.githubusercontent.com/11276349/188250058-f2815617-f6cd-4173-9e38-5d8b1bb47b7b.png">

The fancy option adds a 3px-wide vertical blue line next to the selected result where the line spans the height of the selected result. Such a highlight is more visible than the currently-used arrow.

**Comment by infokiller** [comment]
The extension supports custom CSS rules (see the experimental section in the extension options). Can you try to use that to implement this?

**Comment by MahdiNazemi** [comment]
I tried that before posting this feature request here, but I had no luck. I will give it another shot and report back here if I find a solution.

**Comment by MahdiNazemi** [comment]
I could partially get it to work by adding the following CSS:

```css

.wsn-google-focused-link {
    border-left: 3px solid #2586fc !important;
    transform: translate(-3px, 0) !important;
    padding-left: 8px;
    margin-left: -11px;
}
```

The only problem I have noticed is that the padding and margin settings do not apply to results with a video preview from YouTube.

**Comment by infokiller** [comment]
Thanks for trying this. For videos results, you probably need to override the CSS of `wsn-google-focused-card` (some Google result types have a different CSS class, you can find them by searching for `google` in the CSS).

I'll try to make it work when I get some free time and let you know if I succeed, but that may take a while (I'm far from a CSS expert)

**Comment by MahdiNazemi** [comment]
Thanks for the hint. I tried a few things, but none of them worked.

I'm in the same boat; I will continue to try to resolve the issue and share a working solution if I find one.

**Comment by MahdiNazemi** [comment]
This seems to work for all cases so far:

```css
.wsn-google-focused-link::before,
.wsn-google-focused-map::before {
    border-left: 3px solid #2586fc !important;
    content:"";
    display:block;
    height:100%;
    margin-right: 10px;
    left: -10px;
    position: absolute;
}
```
